# Generated by Django 4.2.7 on 2023-11-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(default='Jugador', max_length=255),
        ),
    ]
