# Generated by Django 4.2.7 on 2023-11-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(db_column='ID_ROL', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100, unique=True)),
                ('descripcion', models.TextField(db_column='DESCRIPCION', max_length=2000)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
            ],
            options={
                'verbose_name': 'ROL',
                'verbose_name_plural': 'ROLES',
                'db_table': 'ROL',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='users.rol'),
        ),
    ]
