# Generated by Django 4.2.7 on 2023-11-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estaditicas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
