# Generated by Django 4.2.7 on 2023-11-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_estaditicas_user_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='estaditicas',
            new_name='estadisticas',
        ),
    ]
