# Generated by Django 4.2.7 on 2023-11-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
